### ISSUE TITLE
Missing git-submodules? 

### ISSUE THREAD

**Issue by NebiyouTen** [YBGou/2024-ICML-TAO#1]
Thank you for sharing your amazing work and providing the source code.

I tried to run the project, but unfortunately, the GDP and IQA-PyTorch directories/submodule links are missing. Could you please share these directories? Or were there no changes from their respective original repositories?

Thanks,
Nebiyou

**Comment by YBGou** [comment]
Thanks for your attention. I didn't make any changes to their respective original repositories. I have fixed the missing submodules due to the nested repository. Perhaps you can enter the folder `gen_dif_pri` to run the initialization via

    pip install -e .

and enter the folder `img_qua_ass` to run the initialization via

    python setup.py develop

**Comment by NebiyouTen** [comment]
Thank you for the prompt response. I can run the project now.
